theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
auto-format = false
cursorline = true
bufferline = "always"
end-of-line-diagnostics = "hint"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name"]
right = ["file-line-ending", "total-line-numbers", "position-percentage"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'`' = '`'

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"
